import AppLoader from '../components/AppLoader';
import {useState} from 'react';
import {useForm} from 'react-hook-form';
import {useNavigate,useParams,useLocation,Link} from 'react-router-dom';
import {ArrowRight,ShieldCheck,CheckCircle2} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {Brand,Field,ErrorState,DataState,time} from '../components/UI';
import {post,message} from '../services/api';
import {useData} from '../hooks/useData';
export function Login(){const {login}=useAuth(),navigate=useNavigate(),location=useLocation(),[error,setError]=useState('');const {register,handleSubmit,formState:{isSubmitting}}=useForm();return <div className="auth-page"><div className="auth-story"><Brand/><div><div className="eyebrow">CARE BEYOND THE CLASSROOM</div><h1>A safer campus.<br/>One verified<br/><em>movement at a time.</em></h1><p>Student departures, parent approvals and gate security, connected in one trusted workspace.</p><div className="auth-features"><span><ShieldCheck/> Verified parent approvals</span><span><CheckCircle2/> Complete movement history</span></div></div><small>Kanhra-Badhra Road · Charkhi Dadri · Haryana</small><div className="orbit one"/><div className="orbit two"/></div><div className="auth-form"><div className="login-card"><span className="pill">SRPS SMART GATE PASS</span><h2>Welcome back.</h2><p>Sign in to your school workspace.</p><form onSubmit={handleSubmit(async values=>{setError('');try{await login(values);navigate(location.state?.from||'/');}catch(e){setError(message(e));}})}><Field label="Email or employee ID"><input autoComplete="username" placeholder="Enter your email or employee ID" {...register('identifier',{required:true})}/></Field><Field label="Password"><input type="password" autoComplete="current-password" placeholder="Enter your password" {...register('password',{required:true})}/></Field>{error&&<ErrorState error={error}/>}<button className="button primary full" disabled={isSubmitting}>{isSubmitting&&<AppLoader inline label="Processing…"/>}{isSubmitting?'Signing in…':'Sign in securely'}<ArrowRight size={18}/></button></form><p className="muted small">Forgot your password? Contact your school administrator for a secure recovery link.</p><div className="login-footer"><ShieldCheck size={16}/> Authorized school staff only</div></div></div></div>;}
export function ResetPassword(){const {token}=useParams(),{register,handleSubmit,formState:{isSubmitting}}=useForm(),[done,setDone]=useState(false),[error,setError]=useState('');return <div className="public-page"><Brand/><section className="card"><h1>Reset your password</h1>{done?<><p>Your password has been updated.</p><Link className="button primary" to="/login">Sign in</Link></>:<form onSubmit={handleSubmit(async values=>{try{await post('/auth/reset-password',{token,password:values.password});setDone(true);}catch(e){setError(message(e));}})}><Field label="New password · at least 12 characters"><input type="password" minLength={12} required {...register('password')}/></Field>{error&&<ErrorState error={error}/>}<button className="button primary" disabled={isSubmitting}>{isSubmitting&&<AppLoader inline label="Processing…"/>}Update password</button></form>}</section></div>;}
export function ParentApproval(){const {token}=useParams(),query=useData(`/parent/${token}`),[done,setDone]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function decide(decision){setBusy(true);try{await post(`/parent/${token}`,{decision});setDone(decision);}catch(e){setError(message(e));}finally{setBusy(false);}}return <div className="public-page"><Brand/><section className="card"><div className="eyebrow">PARENT AUTHORIZATION</div><h1>Gate pass approval</h1>{done?<><CheckCircle2 size={44} color="#168168"/><h2>{done==='approve'?'Thank you. Approval recorded.':'Request declined.'}</h2><p>{done==='approve'?'The school administrator will review the request before departure.':'The student is not authorized to leave on this pass.'}</p></>:<DataState query={query}>{query.data&&<><h2>{query.data.student}</h2><p>{query.data.className} · {query.data.passNumber}</p><dl><dt>Reason</dt><dd>{query.data.reason}</dd><dt>Requested exit</dt><dd>{time(query.data.requestedExit)}</dd><dt>Accompanying person</dt><dd>{query.data.guardian}</dd></dl><p>Approve only if you authorize this departure and accompanying person.</p>{error&&<ErrorState error={error}/>}<div className="actions"><button className="button primary" disabled={busy} onClick={()=>decide('approve')}>{busy&&<AppLoader inline label="Processing…"/>}Approve departure</button><button className="button danger" disabled={busy} onClick={()=>decide('reject')}>{busy&&<AppLoader inline label="Processing…"/>}Decline</button></div></>}</DataState>}</section></div>;}

export function ParentPass(){const {token}=useParams(),query=useData(`/parent/pass/${token}`),p=query.data;return <div className="public-page"><Brand/><section className="card"><div className="eyebrow">DIGITAL STUDENT GATE PASS</div><DataState query={query}>{p&&<><h1>{p.student}</h1><p>{p.className} · {p.admissionNumber}</p><strong>{p.passNumber}</strong><div className="visitor-print"><img src={p.qr} alt="Present this QR code to school security" width="240"/></div><dl>{[['Status',p.status.replaceAll('_',' ')],['Reason',p.reason],['Authorized person',p.guardian],['Requested exit',time(p.requestedExit)],['Expected return',p.expectedReturn?time(p.expectedReturn):'No return required'],['Approved by',p.approvedBy]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>Present this QR to school security. Security must confirm the live status and student identity before departure.</p><button className="button primary full no-print" onClick={()=>window.print()}>Print gate pass</button></>}</DataState></section></div>;}
